#!/usr/bin/env bash
# test_decide_service.sh - the decision gateway and encoder runtime as boot-time
# user services on both OSes (spec 009 FR-031, FR-083, G-028, G-041, T080/T081).
#
# Linux: the generated systemd user units are inspected AND checked by
# `systemd-analyze --user verify` (unknown keys are the failure mode that
# silently dropped StartLimitIntervalSec); the lifecycle commands go through
# the dry-run backend. The per-start key rotation hook runs for real.
#
# macOS: NO Mac is available to this suite. launchctl is therefore never
# executed; the LaunchAgent files are generated by the real backend code and
# validated structurally (python plistlib, mode, ProgramArguments array,
# KeepAlive/ThrottleInterval, absence of key material) plus the dry-run
# launchctl command lines. That is a file-content check, NOT proof that launchd
# accepts and runs the agents - recorded honestly in the QA evidence (gap G-009;
# registry liveness on macOS uses `ps -o args=` and is fixture-tested only).
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"
test_setup_env
trap test_teardown_env EXIT

command -v python3 >/dev/null 2>&1 || { echo "SKIP-SUITE: python3 not installed"; exit 0; }

export LLMCTL_DRY_RUN=1
export LLMCTL_FAKE_HW="${LLMCTL_ROOT}/tests/fixtures/hw-baseline.json"
# the unit only needs the NAME of an executable; a real file is enough (no network, no run)
mkdir -p "${TEST_TMP}/bin"
printf '#!/bin/sh\nexit 0\n' > "${TEST_TMP}/bin/llmctl-decide"; chmod +x "${TEST_TMP}/bin/llmctl-decide"
export LLMCTL_DECIDE_BIN="${TEST_TMP}/bin/llmctl-decide"
export LLMCTL_PORTREG=0   # path discovery only; nothing is allocated here

sect_of() { awk -v key="$2" 'BEGIN{s=""} /^\[/{s=$0} index($0,key"=")==1{print s; exit}' "$1"; }

echo "== Linux: gateway unit (decide_service_enable) =="
out="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/os_detect.sh"
  source "${LLMCTL_ROOT}/lib/hardware.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  decide_service_enable 2>&1
)"
GU="${LLMCTL_UNIT_DIR}/llmctl-decide-gateway.service"
# since 51a6a8c (G-069) a dry run writes NO unit file (tests/test_decide_serve_enable.sh owns that contract and the
# real, stubbed-systemctl enable); the unit content below comes from the same generator the real enable calls
assert_file_absent "${GU}" "dry-run enable wrote no unit file"
assert_contains "${out}" "[dry-run] write ${GU}" "dry-run enable says what it would write"
assert_contains "${out}" "[dry-run] systemctl --user enable llmctl-decide-gateway.service" "enable goes through the service manager"
assert_contains "${out}" "[dry-run] systemctl --user start llmctl-decide-gateway.service" "…and starts it"
assert_contains "${out}" "[dry-run] systemctl --user daemon-reload" "…after a daemon-reload"
wrote="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/os_detect.sh"
  source "${LLMCTL_ROOT}/lib/hardware.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  _decide_gateway_write_unit
)"
assert_eq "${GU}" "${wrote}" "the unit generator writes the gateway unit into the user unit dir"
assert_file_exists "${GU}" "gateway unit written"
assert_file_contains "${GU}" "Restart=always" "Restart=always"
assert_file_contains "${GU}" "RestartSec=5" "RestartSec=5"
assert_file_contains "${GU}" "WantedBy=default.target" "starts at login/boot (with linger)"
assert_file_contains "${GU}" "svc_hook.sh\" run-gateway" "ExecStart is the wrapper that allocates the port then execs: llmctl-decide serve --foreground"
assert_file_contains "${GU}" "serve --foreground" "the unit documents the final exec"
assert_file_contains "${GU}" "Environment=\"LLMCTL_DECIDE_BIN=${LLMCTL_DECIDE_BIN}\"" "the binary path is baked, resolved at install time"
assert_file_contains "${GU}" "EnvironmentFile=-${LLMCTL_STATE_DIR}/decide/gateway.conf" "optional operator overrides file (port/bind/strategy)"
assert_file_contains "${GU}" "svc_hook.sh\" unregister gateway" "ExecStopPost removes the registry row"
assert_eq "[Unit]" "$(sect_of "${GU}" StartLimitIntervalSec)" "StartLimitIntervalSec is in [Unit] (honoured there)"
assert_eq "[Unit]" "$(sect_of "${GU}" StartLimitBurst)" "StartLimitBurst is in [Unit]"
# OD-14 (2026-09-15): no artificial ceiling below the machine: MemoryMax = MemoryHigh = probed total
assert_file_contains "${GU}" "MemoryMax=32768M" "memory policy OD-14: MemoryMax = full probed RAM"
assert_file_contains "${GU}" "MemoryHigh=32768M" "memory policy OD-14: MemoryHigh = MemoryMax (no soft throttle)"
# no secret in the unit
if grep -Eq '[0-9a-f]{40,}|API_KEY|PASSWORD|TOKEN=' "${GU}"; then printf '  FAIL: key-like material in the gateway unit\n' >&2; TEST_FAILS=$((TEST_FAILS+1)); else printf '  ok: no key material / credential variable in the unit\n'; fi

echo "== Linux: engine templates (decision engines share them) =="
(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/os_detect.sh"
  source "${LLMCTL_ROOT}/lib/hardware.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  svc_install
) >/dev/null 2>&1
for t in llama onnx colibri; do
  U="${LLMCTL_UNIT_DIR}/llmctl-${t}@.service"
  assert_eq "[Unit]" "$(sect_of "${U}" StartLimitIntervalSec)" "${t} template: StartLimitIntervalSec in [Unit]"
  assert_eq "[Unit]" "$(sect_of "${U}" StartLimitBurst)" "${t} template: StartLimitBurst in [Unit]"
  assert_file_contains "${U}" "svc_hook.sh\" prestart %i" "${t} template: per-start key rotation (ExecStartPre)"
  assert_file_contains "${U}" "svc_hook.sh\" register %i" "${t} template: registry publication (ExecStartPost)"
  assert_file_contains "${U}" "svc_hook.sh\" unregister %i" "${t} template: registry removal (ExecStopPost)"
  assert_file_contains "${U}" "NoNewPrivileges=yes" "${t} template: NoNewPrivileges"
done
assert_file_contains "${LLMCTL_UNIT_DIR}/llmctl-onnx@.service" "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6" "encoder runtime template carries the strict set"
if grep -q "RestrictAddressFamilies" "${LLMCTL_UNIT_DIR}/llmctl-llama@.service"; then printf '  FAIL: chat/GPU engine template must not get the address-family restriction\n' >&2; TEST_FAILS=$((TEST_FAILS+1)); else printf '  ok: llama template keeps the basic set only\n'; fi
# directives the user manager does NOT honour must not be claimed (measured: tests/test_unit_hardening.sh)
for bad in PrivateTmp ProtectHome ProtectControlGroups ProtectProc PrivateDevices ProtectClock CapabilityBoundingSet; do
  if grep -q "^${bad}=" "${GU}" "${LLMCTL_UNIT_DIR}"/llmctl-*@.service; then printf '  FAIL: %s written although the user manager does not honour it\n' "${bad}" >&2; TEST_FAILS=$((TEST_FAILS+1)); fi
done
printf '  ok: no un-honoured hardening directive is claimed in any unit\n'

if command -v systemd-analyze >/dev/null 2>&1; then
  echo "== Linux: systemd-analyze --user verify (unknown keys = silently ignored settings) =="
  # control needle: the same check MUST flag a unit that has the historical defect
  # (StartLimitIntervalSec in [Service]); otherwise a clean result proves nothing
  printf '[Unit]\nDescription=x\n[Service]\nExecStart=/bin/true\nStartLimitIntervalSec=60\n' > "${TEST_TMP}/needle.service"
  nout="$(systemd-analyze --user verify "${TEST_TMP}/needle.service" 2>&1 || true)"
  if grep -q "needle.service.*\(Unknown\|unknown\|ignoring\)" <<<"${nout}"; then printf '  ok: control needle - the verify check flags a known-bad unit\n'; else printf '  FAIL: control needle not detected; the verify check is blind here\n' >&2; TEST_FAILS=$((TEST_FAILS+1)); fi
  for U in "${GU}" "${LLMCTL_UNIT_DIR}"/llmctl-{llama,onnx,colibri}@.service; do
    vout="$(systemd-analyze --user verify "${U}" 2>&1 || true)"
    if grep -q "${U}.*Unknown\|${U}.*unknown\|${U}.*ignoring" <<<"${vout}"; then
      printf '  FAIL: systemd rejected/ignored settings in %s:\n%s\n' "$(basename "${U}")" "${vout}" >&2; TEST_FAILS=$((TEST_FAILS+1))
    else
      printf '  ok: %s: no unknown or ignored keys\n' "$(basename "${U}")"
    fi
  done
else
  assert_skip "systemd-analyze not installed" "unit verification"
fi

echo "== Linux: disable removes the unit and the registry/port state =="
out="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/os_detect.sh"
  source "${LLMCTL_ROOT}/lib/hardware.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  decide_service_disable 2>&1; decide_service_status 2>&1
)"
# C-12: a DRY run never deletes the real unit (the service would keep running without its unit file)
assert_file_exists "${GU}" "dry-run disable leaves the unit file alone"
assert_contains "${out}" "[dry-run] rm -f ${GU}" "...and says what it would remove"
printf '#!/usr/bin/env bash\nexit 0\n' > "${TEST_TMP}/systemctl"; chmod +x "${TEST_TMP}/systemctl"
(
  export LLMCTL_DRY_RUN=0 PATH="${TEST_TMP}:${PATH}"
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/os_detect.sh"
  source "${LLMCTL_ROOT}/lib/hardware.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  decide_service_disable >/dev/null 2>&1
)
assert_file_absent "${GU}" "gateway unit removed by a real disable"
assert_contains "${out}" "[dry-run] systemctl --user stop llmctl-decide-gateway.service" "stopped"
assert_contains "${out}" "[dry-run] systemctl --user disable llmctl-decide-gateway.service" "disabled"
assert_contains "${out}" "[dry-run] systemctl --user status llmctl-decide-gateway.service" "status goes through the service manager"

echo "== per-start key rotation hook (G-028) =="
KEYF="${LLMCTL_STATE_DIR}/keys/llama-rot.key"
(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_linux.sh"
  svc_write_env rot llama /opt/x/llama-server --port 9 --api-key-file "${KEYF}"
  svc_write_env nokey llama /opt/x/llama-server --port 10
)
umask 022
bash "${LLMCTL_ROOT}/lib/svc_hook.sh" prestart rot
K1="$(cat "${KEYF}")"
bash "${LLMCTL_ROOT}/lib/svc_hook.sh" prestart rot
K2="$(cat "${KEYF}")"
if [[ -n "${K1}" && -n "${K2}" && "${K1}" != "${K2}" ]]; then printf '  ok: every start gets a NEW key (not create-if-absent)\n'; else printf '  FAIL: key was not rotated (%s)\n' "${K1:+non-empty}" >&2; TEST_FAILS=$((TEST_FAILS+1)); fi
assert_eq "600" "$(stat -c %a "${KEYF}")" "rotated key file is mode 0600 even under umask 022"
assert_eq "700" "$(stat -c %a "$(dirname "${KEYF}")")" "key directory is mode 0700"
assert_eq "64" "$(tr -d '\n' < "${KEYF}" | wc -c | tr -d ' ')" "key is 256 bits of /dev/urandom (64 hex chars)"
rc=0; bash "${LLMCTL_ROOT}/lib/svc_hook.sh" prestart nokey || rc=$?
assert_eq 0 "${rc}" "a service without a key file: the hook is a no-op that succeeds"
rc=0; bash "${LLMCTL_ROOT}/lib/svc_hook.sh" prestart does-not-exist || rc=$?
assert_eq 0 "${rc}" "an unknown instance is a no-op too (never blocks a start)"
umask 077

echo "== macOS: launchd agents (file-content validation; NO Mac available) =="
PL="${LLMCTL_PLIST_DIR}/com.llmctl.decide-gateway.plist"
out="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_macos.sh"
  decide_service_enable 2>&1
)"
assert_file_absent "${PL}" "dry-run enable wrote no plist"
assert_contains "${out}" "[dry-run] write ${PL}" "dry-run enable says what it would write"
assert_contains "${out}" "[dry-run] launchctl bootstrap" "bootstrap goes through launchctl (dry-run line)"
wrote="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_macos.sh"
  _decide_gateway_write_plist
)"
assert_eq "${PL}" "${wrote}" "the plist generator writes the gateway agent into the LaunchAgents dir"
assert_file_exists "${PL}" "gateway agent written"
assert_eq "600" "$(stat -c %a "${PL}")" "gateway plist is mode 0600"
python3 -I - "${PL}" "${LLMCTL_ROOT}" <<'PY' && printf '  ok: gateway plist structure (plistlib)\n' || { printf '  FAIL: gateway plist structure\n' >&2; TEST_FAILS=$((TEST_FAILS+1)); }
import plistlib, re, sys
d = plistlib.load(open(sys.argv[1], "rb"))
assert d["Label"] == "com.llmctl.decide-gateway", d["Label"]
pa = d["ProgramArguments"]
assert isinstance(pa, list) and pa[0] == "/bin/bash" and pa[-1] == "run-gateway" and pa[1].endswith("lib/svc_hook.sh"), pa
assert d["KeepAlive"] is True and d["RunAtLoad"] is True
assert isinstance(d["ThrottleInterval"], int) and d["ThrottleInterval"] >= 10, d["ThrottleInterval"]
env = d["EnvironmentVariables"]
assert env["LLMCTL_DECIDE_BIN"].endswith("llmctl-decide")
blob = repr(d)
assert not re.search(r"[0-9a-f]{40,}", blob), "key-like hex in plist"
assert not any("KEY" in k or "TOKEN" in k or "PASSWORD" in k for k in env), sorted(env)
assert d["StandardOutPath"].endswith("decide-gateway.log")
PY
(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_macos.sh"
  svc_write_env decide-nli onnx /usr/bin/python3 /srv/lib/onnx_server.py --model-dir /m --host 127.0.0.1 --port 8096 --profile decide-nli --api-key-file "${LLMCTL_STATE_DIR}/keys/onnx-decide-nli.key"
)
EP="${LLMCTL_PLIST_DIR}/com.llmctl.decide-nli.plist"
assert_eq "600" "$(stat -c %a "${EP}")" "encoder-runtime plist is mode 0600"
python3 -I - "${EP}" <<'PY' && printf '  ok: encoder runtime plist structure (plistlib)\n' || { printf '  FAIL: encoder runtime plist structure\n' >&2; TEST_FAILS=$((TEST_FAILS+1)); }
import plistlib, re, sys
d = plistlib.load(open(sys.argv[1], "rb"))
pa = d["ProgramArguments"]
# C-13: the engine runs through `svc_hook.sh run-engine <profile> -- <engine command>` so that a launchd
# KeepAlive respawn rotates the key and re-registers the service
assert pa[0] == "/bin/bash" and pa[1].endswith("lib/svc_hook.sh") and pa[2:5] == ["run-engine", "decide-nli", "--"], pa
pa = pa[5:]
assert isinstance(pa, list) and pa[0] == "/usr/bin/python3" and "--api-key-file" in pa, pa
assert pa[pa.index("--api-key-file") + 1].endswith("onnx-decide-nli.key")
assert pa[pa.index("--host") + 1] == "127.0.0.1", "encoder runtime must be loopback-only"
assert not [a for a in pa if re.fullmatch(r"[0-9a-f]{32,}", a)], "key material in ProgramArguments"
assert d["KeepAlive"] is True and d["ThrottleInterval"] == 60
PY
assert_file_contains "${LLMCTL_SERVICES_DIR}/decide-nli.env" "LLMCTL_KEY_FILE=" "macOS env record names the key FILE too (rotated before each start)"
out="$(
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_macos.sh"
  decide_service_disable 2>&1; decide_service_status 2>&1
)"
assert_file_exists "${PL}" "dry-run disable leaves the real agent plist alone (C-12)"
printf '#!/usr/bin/env bash\nexit 0\n' > "${TEST_TMP}/launchctl"; chmod +x "${TEST_TMP}/launchctl"
(
  export LLMCTL_DRY_RUN=0 PATH="${TEST_TMP}:${PATH}"
  source "${LLMCTL_ROOT}/lib/common.sh"; source "${LLMCTL_ROOT}/lib/service_macos.sh"
  decide_service_disable >/dev/null 2>&1
)
assert_file_absent "${PL}" "gateway agent removed by a real disable"
assert_contains "${out}" "[dry-run] launchctl bootout" "bootout goes through launchctl"
assert_contains "${out}" "[dry-run] launchctl print" "status goes through launchctl"
assert_skip "no macOS host in this environment" "launchd actually loading/running the agents (bootstrap/KeepAlive behaviour) is NOT exercised; only the generated files and command lines are validated (gap G-009)"

test_finish
